package com.royalcommission.bs.modules.utils;

/**
 * Created by Prashant on 9/9/2018.
 */
public enum DateFormatType {
    FILE_NAME_CREATION,
    CURRENT_DATE,
    CALENDAR_ADAPTER_DATE,
    CURRENT_TIME,
    ALARM_TIME,
    OPERATION_TIME,
    CALENDAR_TITLE_FORMAT,
    PRESCRIPTION_ALARM_FORMAT,
    HOME_PAGE_TIME_FORMAT,
    HOME_PAGE_DATE_FORMAT,
    APPOINTMENT_TIME_SERVER,
    NORMAL_DATE_TIME,
    APPOINTMENT_HISTORY_FORMAT,
    DATE_MONTH_FORMAT,
    APPOINTMENT_DATE,
    VACCINATION_DATE,
    EXPIRY_DATE,
    APPOINTMENT_TIME,
    DUMMY_APPOINTMENT_TIME,
    EXERCISE_DATE,
    DEFAULT
}
